### PR TITLE
Add replay support

### PR DESCRIPTION
**Pull request by LumpBloom7**
This should add basic support for replays.

### CODE REVIEW

**Comment by LumpBloom7** [comment]
RX currently doesn't work well at all with autoplay.

Relax mod is trying to interfere when playing back a replay that was recorded while using Relax, breaking replays. I think the same problem might also be affecting osu!std on lazer..

**Comment by LumpBloom7** [comment]
Fk accidental close

**Comment by Coppertine** [comment]
I think it's best to include a relax testscene to get the error

**Comment by LumpBloom7** [comment]
I don't think it's the fault of RX mod input directly, nothing I can change on that end I think.
It's just RX trying to do its thing while the replay is playing, and both replay frame input and RX input conflict.

**Pull request merged**
