### PR TITLE
Implement HitObject pooling

### PR DESCRIPTION
**Pull request by LumpBloom7**
Opening this here for CI checks, and for third party feedback

**Pooled objects:**
- [x] Tap
- [x] Hold
- [x] ScorePadding
- [x] Slide
- [x] SlideBody
- [x] SlideTap
- [x] Touch
- [x] TouchHold
- [x] HoldHead
- [x] SlideNodes

Other problems:
 * ~~SlideBody and SlideTap colours are super fucked...~~ FIXED
 * ~~Rewind creates ghost objects (osu-side problem)~~ FIXED IN https://github.com/ppy/osu/pull/10961

### CODE REVIEW

**Comment by LumpBloom7** [comment]
Having a bit of a problem with the same DrawableSlideNode being added to DrawableSlideBody.
image

**Comment by smoogipoo** [comment]
Is the issue here that you're doing `Clear()` in `ClearNestedHitObjects` instead of `Clear(false)`?

**Comment by LumpBloom7** [comment]
No, the `Clear(false)`  is correctly used.
The problem happens on the exact same DHO use. I'm currently investigating whether I've missed something somewhere.

**Comment by LumpBloom7** [comment]
This is the sequence I've obtained via break pointing on the first slide occurrence, using `GetHashCode()` to accurately identify which is what.
```
SlideBody.Node (Node.HitObject) => Parent.HitObject

25954490 (58461314) => 11659220
25954490 (9320303) => 11659220 [CRASH]
```
Tested on this commit: <https://github.com/LumpBloom7/sentakki/commit/72c939ab686e69d18e7fb7c936ac09d59906532c>

Not sure if it matters, but the nesting is at level 3 with SlideNodes. (Slide > SlideBody(s) > SlideNodes)

**Comment by smoogipoo** [comment]
Can't see anything wrong from the code, you'd have to dig deeper I'm afraid.

**Comment by LumpBloom7** [comment]
Yes, I'm in the process of doing so. Need to get a local checkout to breakpoint osu-side code. Will report in lazer discord if I find anything.

**Comment by LumpBloom7** [comment]
@smoogipoo 
Okay. I figured out the root cause of the problem.
The node is being returned earlier than expected. I initially thought it was some lifetime screwup somewhere, but temporarily unsealing, overriding, and adding a breakpoint to `FreeAfterUse` in `DrawableSlideNode` shows the main point of failure... In a most unexpected spot too...

https://github.com/LumpBloom7/sentakki/blob/SlideNodePooling/osu.Game.Rulesets.Sentakki/Objects/Drawables/DrawableSlideNode.cs#L53

So general gist of what I think is going on is 

DrawableSlideBody(a) requests a `DrawableSlideNode`(DSN), the DSN is fetched **AFTER** `DSN.Apply()` is called. The apply method loads the samples and encounters that line... `AddInternal` triggers a parent invalidation, which `PoolableDrawable` overridden so the object gets `Return()` instead since the DSN doesn't have a parent yet...

https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Pooling/PoolableDrawable.cs#L117

Removing the sample addition resolves that specific issue... (It still crashes because of an oversight in that branch, different reason tho)

**Comment by smoogipoo** [comment]
Sorry for the late reply (weekend). Good stuff on the investigation - turns out this is a bug in PoolableDrawable which I'll fix.

**Pull request merged**
